//package com.dreamshops.dynamoDB.product;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//import lombok.AllArgsConstructor;
//import lombok.Getter;
//import lombok.NoArgsConstructor;
//import lombok.Setter;
//
//import java.math.BigDecimal;
//
//@Getter
//@Setter
//@AllArgsConstructor
//@NoArgsConstructor
//@DynamoDBTable(tableName = "Product")
//public class DynamoProduct {
//
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    private String id;
//
//    @DynamoDBAttribute(attributeName = "product_name")
//    private String name;
//
//    @DynamoDBAttribute(attributeName = "product_brand")
//    private String brand;
//
//    @DynamoDBAttribute(attributeName = "product_price")
//    private BigDecimal price;
//
//    @DynamoDBAttribute(attributeName = "product_inventory")
//    private int inventory;
//
//    @DynamoDBAttribute(attributeName = "product_description")
//    private String description;
//
//    @DynamoDBAttribute(attributeName = "category")
//    private ProductCategory category;
//}
