name: CI/CD to Render

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Give Maven Wrapper permission
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test

      - name: Build application
        run: ./mvnw clean package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Deploying to Render service $RENDER_SERVICE_ID..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
               -H 'Accept: application/json' \
               -H "Authorization: Bearer ${RENDER_API_KEY}" \
               -H 'Content-Type: application/json' \
               -d '{}'
